spring:
  profiles:
    group:
      "local": "local"
      "dev": "dev"
    include: oauth

---

spring:
  config:
    activate:
      on-profile: "local"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: com.root.pilot.config.MySQL8DialectCustom
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/pilot
    username: root
    password: qwer1234
  thymeleaf:
    cache: false
logging:
  level:
    com.root.pilot: debug

---

spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: com.root.pilot.config.MySQL8DialectCustom
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.200.3.132:13306/rootpilot
    username: puser
    password: qwer1234
  thymeleaf:
    cache: false
logging:
  level:
    com.root.pilot: debug


