spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: com.root.pilot.config.MySQL8DialectCustom
        default_batch_fetch_size: 100
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/pilot
    username: root
    password: qwer1234
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      connection-test-query: select 1
  sql:
    init:
      mode: EMBEDDED
  thymeleaf:
    cache: false
logging:
  level:
    com.root.pilot: debug


