spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  profiles:
    include: oauth

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pilot
    username: test
    password: 1234

  sql:
    init:
      mode: EMBEDDED

  thymeleaf:
    cache: false

logging:
  level:
    com.root.pilot: debug


