spring:
  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pilot
    username: test
    password: 1234
  thymeleaf:
    cache: false